<?php

use Illuminate\Database\Seeder;

class SubjectsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('sub_subjects')->delete();
        \DB::table('subjects')->delete();

        $subjects = [
            'Concours - Bac' =>
                [
                    'Bac',
                    'Brevet',
                    'CPGE',
                    'EGE Rabat',
                    'ENA(administration) Rabat',
                    'ENA Architecture Rabat',
                    'ENAM Meknès',
                    'ENCG',
                    'ENSA',
                    'ENSAM',
                    'ERSSM',
                    'FMD',
                    'FMP',
                    'HEM',
                    'IAV',
                    'INPT Rabat',
                    'ISCAE',
                    'ISEM Casablanca',
                    'ISIT Tanger',
                    'Grandes écoles',
                    'Préparation aux Masters',
                    'IELTS',
                    'DELF',
                    'PET',
                    'DALF',
                    'CELTA',
                    'GMAT',
                    'TOEFL',
                ],

            'Soutien scolaire'  =>
                [
                    'Aide aux devoirs',
                    'Algèbre',
                    'Arabe',
                    'Arithmétique',
                    'Art conception de l’environnement',
                    'Art conception de la communication',
                    'Art conception des produits',
                    'Biologie',
                    'Chimie',
                    'Conjugaison',
                    'Culture générale',
                    'Economie générale et statistiques',
                    'Français',
                    'Géographie',
                    'Grammaire',
                    'Hadiths',
                    'Histoire',
                    'Lettres',
                    'Mathématiques',
                    'Philosophie',
                    'Physique',
                    'Sciences de l\'ingénieur',
                    'Sciences végétales et animales',
                    'Statistiques',
                    'Sciences et Vie de la Terre',
                    'Tafssir',
                ],
            'Sciences'          =>
                [
                    'Algèbre',
                    'Anatomie',
                    'Arithmétique',
                    'Développement durable',
                    'Électricité',
                    'Énergies renouvelables',
                    'Géologie',
                    'Mathématiques',
                    'Mécanique',
                    'Médecine',
                    'Paramédical',
                    'Pharmacie',
                    'Sciences médico-sociales',
                    'Sciences végétales et animales',
                    'Statistiques',

                ],
            'Economie'          =>
                [
                    'Audit et contrôle de gestion',
                    'Commerce',
                    'Communication',
                    'Comptabilité',
                    'Création d\'entreprise',
                    'Économie',
                    'Economie générale et statistiques',
                    'Finance',
                    'Fiscalité',
                    'Gestion comptable',
                    'Gestion de projet',
                    'Gestion des risques',
                    'Logistique',
                    'Macroéconomie',
                    'Management et gestion d\'entreprise',
                    'Marketing',
                    'Microéconomie',
                    'Ressources Humaines',
                    'Statistiques',
                ],
            'Langues'           =>
                [
                    'Allemand',
                    'Anglais',
                    'Arabe',
                    'Chinois',
                    'Coréen',
                    'Darija',
                    'Espagnol',
                    'Français',
                    'Grec',
                    'Indonésien',
                    'Italien',
                    'Japonais',
                    'Langue des signes',
                    'Malais',
                    'Persan',
                    'Portugais',
                    'Russe',
                    'Turc',
                    'Amélioration d\'accent français',
                    'Amélioration d\'accent anglais',
                    'Amélioration d\'accent espagnol',
                ],
            'Droit'             =>
                [
                    'Droit administratif',
                    'Droit civil',
                    'Droit constitutionnel',
                    'Droit de la Propriété intellectuelle',
                    'Droit des affaires',
                    'Droit du travail',
                    'Droit européen',
                    'Droit fiscal',
                    'Droit général',
                    'Droit immobilier',
                    'Droit international',
                    'Droit pénal',
                    'Droit public',
                ],
            'Sciences humaines' =>
                [
                    'Archéologie',
                    'Communication',
                    'Culture générale',
                    'Education islamique',
                    'Graphologie',
                    'Journalisme',
                    'Lettres',
                    'Philosophie',
                    'Psychologie',
                    'Relations internationales',
                    'Ressources humaines',
                    'Sciences politiques',
                    'Sciences sociales',
                    'Sociologie',
                ],
            'Informatique'      =>
                [
                    'ACCESS',
                    'Adobe After Effects',
                    'Base de données SQL',
                    'C/C++',
                    'CAO',
                    'CATIA',
                    'Création de site web',
                    'Développement Web',
                    'Dreamweaver',
                    'Électronique',
                    'Excel',
                    'Gestion de projets',
                    'Gestion de réseau',
                    'HTML',
                    'Illustrator',
                    'InDesign',
                    'Infographie',
                    'Initiation informatique',
                    'Initiation Internet',
                    'Informatique de gestion',
                    'Java',
                    'Javascript',
                    'Linux',
                    'Modélisation et Animation 3D',
                    'Montage vidéo',
                    'MYSQL',
                    'PACK Office (Word, excel, powerpoint)',
                    'Photoshop',
                    'PHP',
                    'Powerpoint',
                    'Programmation',
                    'Python',
                    'Référencement',
                    'Retouches photo',
                    'Ruby',
                    'Sécurité informatique',
                    'Système d\'exploitation',
                    'VBA',
                    'Visual BASIC/ASP.NET',
                    'Web Design',
                    'Webmaster',
                    'Word',
                ],
            'Musique'           =>
                [
                    'Accordéon',
                    'Alto',
                    'Autres instruments',
                    'Basse',
                    'Basson',
                    'Batterie',
                    'Chant',
                    'Chant lyrique',
                    'Chorale',
                    'Clarinette',
                    'Composition',
                    'Contrebasse',
                    'Cornemuse',
                    'Derbouka',
                    'Djembé',
                    'Éveil musical',
                    'Flûte',
                    'Flûte piccolo',
                    'Flûte traversière',
                    'Guitare',
                    'Guitare acoustique',
                    'Guitare classique',
                    'Guitare flamenca',
                    'Harmonica',
                    'Harpe',
                    'Hautbois',
                    'Histoire de la musique',
                    'Instruments à cordes',
                    'Instruments à vent',
                    'Luth',
                    'Mandoline',
                    'Melhoune',
                    'Mix - DJ',
                    'Musicothérapie',
                    'Musique arabo-andalouse',
                    'Musique Chaabi',
                    'Musique classique',
                    'Musique électronique',
                    'Musique Gnawa',
                    'Musique Hassanya',
                    'Musique marocaine',
                    'Orgue',
                    'Oud',
                    'Percussions',
                    'Piano',
                    'Qanoun',
                    'Rap',
                    'Reggae',
                    'Rock',
                    'Saxophone',
                    'Solfège',
                    'Synthétiseur',
                    'Trombone',
                    'Trompette',
                    'Viole de Gambe',
                    'Violon',
                    'Violoncelle',

                ],
            'Sports'            =>
                [
                    'Aikido',
                    'Aquagym',
                    'Arts martiaux',
                    'Athlétisme',
                    'Baby-foot',
                    'Badminton',
                    'Basket',
                    'Boxe',
                    'Breakdance',
                    'Capoeira',
                    'Coach sportif',
                    'Comédie musicale',
                    'Course à pied',
                    'Cyclisme',
                    'Danse',
                    'Danse africaine',
                    'Danse bollywood',
                    'Danse classique',
                    'Danse contemporaine',
                    'Danse indienne',
                    'Danse jazz',
                    'Danse moderne',
                    'Danse orientale',
                    'Danses latines',
                    'Echecs',
                    'Équitation',
                    'Escalade',
                    'Escrime',
                    'Fitness',
                    'Football',
                    'Golf',
                    'Gymnastique',
                    'Gymnastique rythmique',
                    'Handball',
                    'Hip hop',
                    'Hockey sur gazon',
                    'Hockey sur glace',
                    'Judo',
                    'Karaté',
                    'Kickboxing',
                    'Massage',
                    'MMA',
                    'Musculation',
                    'Natation',
                    'Nutrition du sport',
                    'PADEL',
                    'Patinage',
                    'Pétanque',
                    'PILATES',
                    'Plongée sous-marine',
                    'Roller',
                    'Rugby',
                    'Salsa',
                    'Self-défense',
                    'Skate',
                    'Ski',
                    'Squash',
                    'Surf',
                    'Tango',
                    'Taekwondo',
                    'Tennis',
                    'Tennis de table',
                    'Triathlon',
                    'Valse',
                    'Volley',
                    'Yoga',
                    'Zumba',
                ],
            'Arts'              =>
                [
                    'Architecture',
                    'Artisanat',
                    'Bande dessinée',
                    'Broderie',
                    'Calligraphie',
                    'Cinéma',
                    'Couture',
                    'Culture artistique',
                    'Design',
                    'Dessin',
                    'Dessin industriel',
                    'Graphisme',
                    'Gravure',
                    'Histoire de l\'art',
                    'Illustration',
                    'Maroquinerie',
                    'Mosaïque',
                    'Peinture',
                    'Photographie',
                    'Poterie',
                    'Sculpture',
                    'Théâtre',
                    'Tissage de tapis',
                ],
            'Loisirs'           =>
                [
                    'Animation d\'évènements',
                    'Apiculture',
                    'Bricolage',
                    'Broderie',
                    'Coiffure',
                    'Composition florale',
                    'Couture',
                    'Cuisine',
                    'Cuisine asiatique',
                    'Cuisine Bio',
                    'Cuisine diététique',
                    'Cuisine du monde',
                    'Cuisine française',
                    'Cuisine italienne',
                    'Cuisine sans gluten',
                    'Cuisine traditionnelle',
                    'Cuisine orientale',
                    'Cuisine marocaine',
                    'Décoration',
                    'Ébénisterie',
                    'Gastronomie',
                    'Gastronomique marocaine',
                    'Gastronomie Orientale',
                    'Gravure',
                    'Jardinage',
                    'Jeux de cartes',
                    'Jeux vidéo',
                    'Kitesurf',
                    'Magie',
                    'Menuiserie',
                    'Mosaïque',
                    'Pâtisserie',
                    'Pâtisserie du monde',
                    'Pâtisserie orientale',
                    'Pâtisserie traditionnelle',
                    'Plomberie',
                    'Rubik\'s cube',
                    'Sophrologie',
                    'Soudure',
                    'Stylisme',
                    'Tapisserie',
                    'Travaux manuels',
                ],
        ];

        $i = 1;
        foreach ($subjects as $subjectTitle => $subsubjects) {
            $parentSubject = \App\Models\Subject::create(['name' => $subjectTitle]);

            foreach ($subsubjects as $subsubject) {
                \App\Models\SubSubject::create(['id'        => $i,
                                                'name'      => $subsubject,
                                                'parent_id' => $parentSubject->id]);
                $i++;
            }
        }
    }
}